In [1]:
import pandas as pd

In [2]:
#read CSV
df = pd.read_csv("https://raw.githubusercontent.com/Pankaj-Str/Complete-Python-Mastery/refs/heads/main/53%20DataSet/credit_card_transactions.csv")
df.head()
 
# other method = copy the link from raw data and paste it at the place of the name of that file in the above code

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location
0,100000,4452,2023-01-01,Online,Walmart,Travel,4520.70,Debit Card,Approved,Jonesport
1,100001,2775,2023-01-01,ATM,BestBuy,Travel,1437.85,Debit Card,Approved,Port Jennifer
2,100002,2259,2023-01-01,Mobile Payment,Uber,Clothing,3320.52,PayPal,Approved,Port James
3,100003,4545,2023-01-01,Online,BestBuy,Travel,2659.96,Debit Card,Approved,Hawkinston
4,100004,2137,2023-01-01,ATM,Amazon,Travel,2517.07,Debit Card,Approved,Matthewland

In [3]:
#check size ie. no of rows and columns
print(df.shape)

(5500, 10)

In [4]:
#print only columns name
df.columns.to_list()

['Transaction_ID',
 'Customer_ID',
 'Transaction_Date',
 'Transaction_Type',
 'Merchant',
 'Category',
 'Amount',
 'Payment_Mode',
 'Transaction_Status',
 'Location']

In [5]:
#to check the summary STATISTICS
df.describe(include='all')

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location
count,5500.000000,5500.000000,5500,5500,5500,5500,5500.000000,5500,5500,5500
unique,NaN,NaN,230,4,7,6,NaN,4,3,4663
top,NaN,NaN,2023-01-01,Online,Uber,Groceries,NaN,PayPal,Approved,Christophermouth
freq,NaN,NaN,24,1453,833,951,NaN,1432,4698,6
mean,102749.500000,2989.954182,NaN,NaN,NaN,NaN,2492.109224,NaN,NaN,NaN
std,1587.857571,1153.928878,NaN,NaN,NaN,NaN,1444.493842,NaN,NaN,NaN
min,100000.000000,1000.000000,NaN,NaN,NaN,NaN,6.550000,NaN,NaN,NaN
25%,101374.750000,1988.000000,NaN,NaN,NaN,NaN,1236.935000,NaN,NaN,NaN
50%,102749.500000,3000.000000,NaN,NaN,NaN,NaN,2502.405000,NaN,NaN,NaN
75%,104124.250000,3990.000000,NaN,NaN,NaN,NaN,3767.957500,NaN,NaN,NaN
max,105499.000000,4998.000000,NaN,NaN,NaN,NaN,4997.490000,NaN,NaN,NaN

In [6]:
df.isnull().sum()

Transaction_ID        0
Customer_ID           0
Transaction_Date      0
Transaction_Type      0
Merchant              0
Category              0
Amount                0
Payment_Mode          0
Transaction_Status    0
Location              0
dtype: int64

In [7]:
df.dtypes

Transaction_ID          int64
Customer_ID             int64
Transaction_Date          str
Transaction_Type          str
Merchant                  str
Category                  str
Amount                float64
Payment_Mode              str
Transaction_Status        str
Location                  str
dtype: object

In [8]:
df['Category'] = df['Category'].fillna('unknown')
df['Payment_Mode'] = df['Payment_Mode'].fillna('unknown')
df['Transaction_Status'] = df['Transaction_Status'].fillna('unknown')
df['Location'] = df['Location'].fillna('unknown')

In [9]:
df.isnull().sum()

Transaction_ID        0
Customer_ID           0
Transaction_Date      0
Transaction_Type      0
Merchant              0
Category              0
Amount                0
Payment_Mode          0
Transaction_Status    0
Location              0
dtype: int64

In [10]:
# convert str from  float columns
df['Amount'] = df['Amount'].astype(float)

In [11]:
df['Amount'] = df['Amount'].fillna(df['Amount'].median)
df.isnull().sum()

Transaction_ID        0
Customer_ID           0
Transaction_Date      0
Transaction_Type      0
Merchant              0
Category              0
Amount                0
Payment_Mode          0
Transaction_Status    0
Location              0
dtype: int64

In [12]:
#convert transaction date into datetime format and extract year ,month,day as new columns
print(df.head()) #print 5 rows
print(df.dtypes) #check datatype

df['Transaction_Date'] = pd.to_datetime(df['Transaction_Date'])
print(df.dtypes) #check datatype

   Transaction_ID  Customer_ID Transaction_Date Transaction_Type Merchant  \
0          100000         4452       2023-01-01           Online  Walmart
1          100001         2775       2023-01-01              ATM  BestBuy
2          100002         2259       2023-01-01   Mobile Payment     Uber
3          100003         4545       2023-01-01           Online  BestBuy
4          100004         2137       2023-01-01              ATM   Amazon

   Category   Amount Payment_Mode Transaction_Status       Location
0    Travel  4520.70   Debit Card           Approved      Jonesport
1    Travel  1437.85   Debit Card           Approved  Port Jennifer
2  Clothing  3320.52       PayPal           Approved     Port James
3    Travel  2659.96   Debit Card           Approved     Hawkinston
4    Travel  2517.07   Debit Card           Approved    Matthewland
Transaction_ID          int64
Customer_ID             int64
Transaction_Date          str
Transaction_Type          str
Merchant                  str
Category                  str
Amount                float64
Payment_Mode              str
Transaction_Status        str
Location                  str
dtype: object
Transaction_ID                 int64
Customer_ID                    int64
Transaction_Date      datetime64[us]
Transaction_Type                 str
Merchant                         str
Category                         str
Amount                       float64
Payment_Mode                     str
Transaction_Status               str
Location                         str
dtype: object

In [13]:
df['Year'] = df['Transaction_Date'].dt.year
df['Month'] = df['Transaction_Date'].dt.month
df['Date'] = df['Transaction_Date'].dt.day

df.head()
#check info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5500 entries, 0 to 5499
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Transaction_ID      5500 non-null   int64
 1   Customer_ID         5500 non-null   int64
 2   Transaction_Date    5500 non-null   datetime64[us]
 3   Transaction_Type    5500 non-null   str
 4   Merchant            5500 non-null   str
 5   Category            5500 non-null   str
 6   Amount              5500 non-null   float64
 7   Payment_Mode        5500 non-null   str
 8   Transaction_Status  5500 non-null   str
 9   Location            5500 non-null   str
 10  Year                5500 non-null   int32
 11  Month               5500 non-null   int32
 12  Date                5500 non-null   int32
dtypes: datetime64[us](1), float64(1), int32(3), int64(2), str(6)
memory usage: 494.3 KB

In [14]:
#retrieve all transactions made in january 2023
jan_2023 = df[(df['Year'] == 2023) & (df['Month'] == 2)]
jan_2023.head()

#create a report
jan_2023.to_csv("feb_2023.csv")

In [15]:
#Find transactions where Amount > 1000 and Transaction_Type is "Online".
high_online_t = df[(df['Amount'] > 1000) & (df['Transaction_Type'] == 'Online')]
print(high_online_t.head())

    Transaction_ID  Customer_ID Transaction_Date Transaction_Type Merchant  \
0           100000         4452       2023-01-01           Online  Walmart
3           100003         4545       2023-01-01           Online  BestBuy
6           100006         1587       2023-01-01           Online  Netflix
14          100014         1855       2023-01-01           Online  Walmart
18          100018         4438       2023-01-01           Online  BestBuy

         Category   Amount Payment_Mode Transaction_Status       Location  \
0          Travel  4520.70   Debit Card           Approved      Jonesport
3          Travel  2659.96   Debit Card           Approved     Hawkinston
6   Entertainment  2309.06   Debit Card           Approved      Scottport
14       Clothing  2365.67  Credit Card           Approved  Catherineland
18         Dining  2930.38          UPI           Approved    Johnsonside

    Year  Month  Date
0   2023      1     1
3   2023      1     1
6   2023      1     1
14  2023      1     1
18  2023      1     1

In [16]:
#Select only Approved transactions from the dataset.
approved_t = df[(df['Transaction_Status'] == 'Approved')]
print(approved_t.head())

   Transaction_ID  Customer_ID Transaction_Date Transaction_Type Merchant  \
0          100000         4452       2023-01-01           Online  Walmart
1          100001         2775       2023-01-01              ATM  BestBuy
2          100002         2259       2023-01-01   Mobile Payment     Uber
3          100003         4545       2023-01-01           Online  BestBuy
4          100004         2137       2023-01-01              ATM   Amazon

   Category   Amount Payment_Mode Transaction_Status       Location  Year  \
0    Travel  4520.70   Debit Card           Approved      Jonesport  2023
1    Travel  1437.85   Debit Card           Approved  Port Jennifer  2023
2  Clothing  3320.52       PayPal           Approved     Port James  2023
3    Travel  2659.96   Debit Card           Approved     Hawkinston  2023
4    Travel  2517.07   Debit Card           Approved    Matthewland  2023

   Month  Date
0      1     1
1      1     1
2      1     1
3      1     1
4      1     1